### ISSUE TITLE
Readers do not handle style and theme change correctly

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#102]
specifically theme does not update alpha correctly...

![image](https://cloud.githubusercontent.com/assets/737638/25044890/dfd4d484-215b-11e7-8ee2-6e7f693357b8.png)

**Comment by dhowe** [comment]
should be fixed in 407fdc2e5ceb842fc7d
@shadoof pls verify and close

**Comment by shadoof** [comment]
Spent some time this and found it fixed. Closing.
