### ISSUE TITLE
Wrong alpha after textChanged

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#103]
To recreate: start the app and switch immediately to 'the Image' text. Note that text may be invisible now (with an alpha of 0.6...)

![image](https://cloud.githubusercontent.com/assets/737638/25059826/7e8e2a62-21c0-11e7-990f-7bd64f8314ef.png)

**Comment by dhowe** [comment]
I believe this has something to do with the fade on 'loading', however I think I've found a workaround...

**Comment by shadoof** [comment]
Can't recreate this. Fixed? Can be closed?

**Comment by dhowe** [comment]
Fixed
