### ISSUE TITLE
CSS warnings on Firefox (priority=tiny)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#112]
![image](https://cloud.githubusercontent.com/assets/737638/25069278/25679e38-22af-11e7-921d-31d55cf9d02c.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/ReadersJS/pull/171 Solved:
COMMENTED-opacity
COMMENTED-transition
appearance
Support for '-moz-border-radius' and '-moz-box-shadow' have been removed from Firefox 13.0, 
Reference: [border-radious](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius?v=control), [box-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow?v=control)

'User-select' need to be kept...
