### ISSUE TITLE
Update website to point to readers-js-live

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#113]
LOCATIONS (others?):

http://thereadersproject.org/elc3.html#ELC3
http://thereadersproject.org/index.html (add link to left nav?)

**Comment by shadoof** [comment]
amended the elc3.html and pushed on the master branch. Make silent edits and then make live (if it isn't live automatically). I'll do more edits on my own branch (of ReadersWeb) and then submit pull requests in the future?

**Comment by dhowe** [comment]
this way is fine, as long as you tell me when to push live (or you can do it)

**Comment by shadoof** [comment]
Better, in terms of workflow, if you check and make live. I've just pushed a sidebar link as requested and if you are happy with these changes, you can make live and then close this.

**Comment by shadoof** [comment]
I suggest making a new live version of the Readers and then also making the link changes to the website that I've made live also. And close this unless there's more you need at the moment.

**Comment by dhowe** [comment]
should both be live

**Comment by shadoof** [comment]
@dhowe I'm not seeing the version of the site with sidebar link and elc3 page referencing the 'Live' sight. Should I reopen? (Opportunity here to disseminate the site to a brunch of relatively cool DH peeps)

**Comment by shadoof** [comment]
Argh, pull request on its way ...

**Comment by shadoof** [comment]
actually just pushed to master

**Comment by dhowe** [comment]
Note that an a merged PR (or a direct push to master) does NOT make changes like on the site. This also requires a git pull from the directory on rednoise

**Comment by shadoof** [comment]
Understood, @dhowe. Unless you want me too, when I make changes to the website I will push to master, but leave you to pull the site on rednoise and make it live (after checking/amending).
