### ISSUE TITLE
Is there an issue with the Mesostic Reader?

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#123]
I don't know, is there?

**Comment by shadoof** [comment]
In my updated branch @dhowe  the Mesostic reader is turned off:
```
    new MesosticReader(pManager.verso).hide(1);
````
? I assumed you were working on it or something.

**Comment by dhowe** [comment]
no, just demonstrating that you can hide() readers for testing...
you can switch it back to 1 or true

**Comment by dhowe** [comment]
done
