### ISSUE TITLE
not sure that the "[?]" on the pop-up Reader enable/disable caption is quite right

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#124]
I confess I read this as uncertainty rather than a link to help. I know there is a design/UI convention for this, but "[?]" did not do it for me. Is there a special character or an emoticon?  ℹ️ℹ︎

**Comment by dhowe** [comment]
At very least the cursor is incorrect, and the text of the question-mark should not be selectable

**Comment by cqx931** [comment]
https://github.com/dhowe/ReadersJS/pull/128
How about an info button?
![image](https://cloud.githubusercontent.com/assets/3056154/25314549/ff88783e-2878-11e7-87e0-b1c0703f544c.png)

**Comment by shadoof** [comment]
I like it!
