### ISSUE TITLE
Inconsistent capitalization in home-page navigation

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#127]
Having only 'Readers Live' capitalized in the top nav looks strange to me. Also strange that we have 'LIVE' on one nav and 'Live' on the other.

![image](https://cloud.githubusercontent.com/assets/737638/25311712/6c8a5806-283a-11e7-9a11-82ff4381be05.png)

**Comment by dhowe** [comment]
I've tried the following (feel free to revert or come up with other solution):

![image](https://cloud.githubusercontent.com/assets/737638/25311778/47c8e436-283c-11e7-8706-79c61e8d98b9.png)

**Comment by shadoof** [comment]
I'm happy with this.
