### ISSUE TITLE
Test: switch tabs while loading files on reader-live on rednoise

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#139]
Make sure that this doesn't throw an error to the console about 'missing Trigrams'

**Comment by cqx931** [comment]
I don't get the trigram error when I switch tabs, instead I see:
![image](https://cloud.githubusercontent.com/assets/3056154/26577836/4d916064-4560-11e7-95c0-bdfa565b442f.png)

**Comment by cqx931** [comment]
close this one, work on trigram in #140
