### ISSUE TITLE
Highlight focused reader in interface readers list

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#14]
if we can do this in a way that is intuitive, then we should prob move the 'focus' option into the individual reader popup next to speed (when focus for one is enabled, focus for the others are disabled)

**Comment by cqx931** [comment]
The most intuitive way for me is to use icon to show the focus status and use on hover text to show "Focus" or "Set to focus"(Maybe you have some better idea on what text should be used here). Either before the reader circle or afterwards.
![image](https://cloud.githubusercontent.com/assets/3056154/23845367/9482acc6-0802-11e7-88ae-e74a3a525a96.png)
![image](https://cloud.githubusercontent.com/assets/3056154/23845375/9e3932ee-0802-11e7-9c61-8764cd5f555c.png)

My opinion is that here will be too much text on the dash board if we use text.
![image](https://cloud.githubusercontent.com/assets/3056154/23845378/a2d91062-0802-11e7-9de7-1b676ab53743.png)

**Comment by dhowe** [comment]
Whatever visual design we use, we need to include a '?' link (similar to adnauseam settings) to explain what 'focus' means. At quick glance it seems 2 visual icons next to each reader is too much. Perhaps something around the colored circle, like a halo effect, to show who has focus?

**Comment by cqx931** [comment]
It is ok to use "halo effect" to show which reader is focused... but how is the focus going to be set then?

**Comment by dhowe** [comment]
not sure, we need some kind of button, perhaps  just a button called "FOCUS" as in the  above diagram that is either disabled (for the focused reader) or active (for the others) ?

**Comment by cqx931** [comment]
Not sure whether we really need a link to explain what 'focus' means... If the explanation can be summarized within one sentence ,it is better to do it with some hover text.(if on hover for a relative long time)

And I still think that a icon would serve the purpose better.
An icon can indicate the focus status and serve as a clickable button at the same time.
If we use "halo", we still need to add extra button to other active readers that are not on focus...

**Comment by dhowe** [comment]
Definition: "The 'focused' reader is always visible and its output it displayed at far right"  ??
@cayley ?

**Comment by shadoof** [comment]
Yes, @dhowe @cqx931  that is fine by me. or "The 'focused' reader is always visible and able to display the text that it is reading. The words it has read recently are monitored separately on the right."

I'll put this in a separate issue but I'm concerned that we should allow a mode that can be full screen and interface-free ('chromeless').

**Comment by dhowe** [comment]
> Yes, @dhowe @cqx931 that is fine by me. or "The 'focused' reader is always visible and able to display the text that it is reading. The words it has read recently are monitored separately on the right.

that is a bit long for a mouse-over text...

**Comment by cqx931** [comment]
How about something like this
1.Use both "FOCUS" tag and halo effect to indicate focused reader
<img width="450" alt="first" src="https://cloud.githubusercontent.com/assets/3056154/23934714/2d878290-0982-11e7-85b9-eba79546264e.png">
2. Hover "FOCUS" to see instruction text
<img width="450" alt="hover" src="https://cloud.githubusercontent.com/assets/3056154/23934717/3232ff04-0982-11e7-8780-37f6e9b501da.png">
3.Selection shows up for other readers
<img width="450" alt="select" src="https://cloud.githubusercontent.com/assets/3056154/23934762/6c36e918-0982-11e7-807c-345b85ec669c.png">
4.Click to confirm the new focus
<img width="450" alt="last" src="https://cloud.githubusercontent.com/assets/3056154/23934775/7ca4e2c8-0982-11e7-9277-be9de59a947a.png">

**Comment by dhowe** [comment]
@shadoof ?

**Comment by dhowe** [comment]
Another option: 
- use only the button/halo (maybe a bit more obvious)
- hover shows 'click to enable/disable, double-click for focus[?]

**Comment by shadoof** [comment]
Yes, use only button but better, I think:
* double-click always enables **and** gives focus (whether or not the reader is enabled)
* single-click always either enables or disables

**Comment by dhowe** [comment]
agreed

**Comment by cqx931** [comment]
Please check a first try of this feature: https://github.com/dhowe/ReadersJS/pulls

Though the text hovered is always "click to disable/enable, double-click for focus [?]".

If the text display is different for reader in different states, the performance would be a bit tricky:
If the user hover it when the reader is active, stay there, click/double click, the hover text need to change accordingly to stay correct. I think that would be too much interaction for hover text.
