### ISSUE TITLE
Trigrams is not defined error

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#140]
Happens when loading index.html page for the first time -- usually a refresh will fix it. I imagine it is in the loader script:

```
readers-app.js:1255 Uncaught ReferenceError: Trigrams is not defined
    at PageManager.layout (readers-app.js:1255)
    at multi-page.js:25
```

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/148

**Comment by dhowe** [comment]
See #149
