### ISSUE TITLE
error message "logToDisplay is not defined"

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersJS#143]
![image](https://cloud.githubusercontent.com/assets/3056154/26760270/a226b464-4946-11e7-9440-0a1a9973d7fa.png)

**Comment by dhowe** [comment]
I don't see this -- are you on 02b1dba3908 ?

**Comment by cqx931** [comment]
yes, I am.

**Comment by cqx931** [comment]
there is no logToDisplay function in the current repo, what is it for?

**Comment by dhowe** [comment]
https://github.com/dhowe/ReadersJS/blob/master/src/readers-app.js#L1107

**Comment by cqx931** [comment]
ok, wrong catch, it seems to be caused by cache. Close
