### ISSUE TITLE
Remaining interface issues

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#145]
<img width="544" alt="untitled" src="https://cloud.githubusercontent.com/assets/737638/26772523/97aba244-49f8-11e7-9d1c-415010db3103.png">

1.  Fix vertical alignment above
2.  Clicking on any part of another reader (either their circles, names, or F/S/speed buttons) should disable the solo on another reader
3. Try lighter font for all buttons
4. Add hover instructions for all buttons

**Comment by cqx931** [comment]
4.What do you mean by 'all buttons'? Only S/F are actually buttons.... or you mean buttons and selects?

**Comment by dhowe** [comment]
yes, buttons and selects

**Comment by cqx931** [comment]
Please let me know if I still miss any alignment here:
Tried lighter font for all selects, also smaller font for selects/buttons for each reader
![image](https://cloud.githubusercontent.com/assets/3056154/26773397/ca609ece-49fd-11e7-8e99-59b7a093a2e3.png)

**Comment by dhowe** [comment]
Looks much better! Can we also try the same text treatment for the Text/Style/Theme options at bottom, just as an experiment?

Also, we need a hover for the colored circles as well (enable/disable)

**Comment by cqx931** [comment]
Colored circles are a bit different than other elements as it is made using pseudo element (:after) in css.
I need to rearrange the dom structure a little bit to achieve this.
One thing I want to double check before working on this is: 
Currently both clicking on the circle and the text can enable/disable readers. Is this correct or we want enable/disable function only for the circle and not for the text?

**Comment by cqx931** [comment]
A preview for the select style: I guess you mean just the text style but not the size here
![image](https://cloud.githubusercontent.com/assets/3056154/26776956/f8f2c6f8-4a0d-11e7-9ada-a1ebbb0c9ae2.png)

**Comment by dhowe** [comment]
That seems better -- can we try without capital letters? Text, Style, Theme?

**Comment by dhowe** [comment]
> Currently both clicking on the circle and the text can enable/disable readers. Is this correct or we want enable/disable function only for the circle and not for the text?

I think only the circle...

**Comment by cqx931** [comment]
I prefer the capital one
![image](https://cloud.githubusercontent.com/assets/3056154/26781302/5f860472-4a20-11e7-91b5-001274479e79.png)

**Comment by dhowe** [comment]
this looks better to me

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/ReadersJS/pull/147

**Comment by cqx931** [comment]
Can this be closed?
