### ISSUE TITLE
allow Option+<circle-click> to turn all readers off in one click

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#150]
what is the use-case here? and what would be the corresponding short-cuts on other platforms ?

**Comment by shadoof** [comment]
Option-<close window/tab>, etc in Mac Finder, Eclipse, etc. etc.

Use-case: I want to turn all the readers off with one click (especially but not exclusively when presenting the readers to an audience)

**Comment by dhowe** [comment]
I meant, what is the equivalent keyboard-shortcut on windows/linux, etc?

**Comment by shadoof** [comment]
Keyboard+mouse shortcut that I am familiar with (but that I use quite often) is:

Hold down option (or alt) key and click on focused 'red-x' or 'x' (close window). This will also close other associated (same program or Finder) windows and tabs. So, the analogy becomes:

Hold down option (or alt) and click on an active reader circle, turning off all readers.

**Comment by dhowe** [comment]
I've never used this particular shortcut (and I don't think its very common), but I guess no harm in including it...

**Comment by cqx931** [comment]
Added in https://github.com/dhowe/ReadersJS/pull/166, please verify @shadoof

**Comment by shadoof** [comment]
verified and closed
