### ISSUE TITLE
Uncaught error after solo'ing a reader then changing texts, then un-solo'ing

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#152]
Uncaught Error: Grid.gridFor(): no grid for RiText: [498,40,'a']
    at Function.Grid.gridFor (readers-app.js:781)
    at SpawningSimpleReader.onEnterCell (spawning-simple-reader.js:47)
    at SpawningSimpleReader.step (readers-app.js:1118)
    at readers-app.js:1123

... will, I think also be caused by any reader turned off when text is changed.

To reproduce:
* launch app
* solo a reader
* change text (e.g. from misspelt to poetic)
* un'solo

**Comment by dhowe** [comment]
@shadoof does this break anything or is it just a spurious error message?

**Comment by dhowe** [comment]
@shadoof please check and close if ok

**Comment by shadoof** [comment]
Seems good to me 👍
