### ISSUE TITLE
Interface Spec

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersJS#159]
1. ReadersOptions(1): 
   - onClick: brings up the interface; clicking anywhere outside the interface or clicking the button again hides it
   - nothing in the interface is mouse-selectable
&nbsp;

1. TextMenu(1): the interface disappears and new text appears
1. StyleMenu(1): controls the opacity of the text in canvas
1. ThemeMenu(1): controls the color theme of the whole web page (interface color is not affected by this setting)
1. FocusDisplay(1)
   - Should clear on any focus change
   - Text within (not title) should be mouse-selectable 
&nbsp;

1. On/off circle(*): The only button to turn on/off a reader
   - The circle glows if it is the current focused reader (Do we still need this? F button should be enough to indicate the current focus)
   - These buttons are always active (even during solo)
&nbsp;

1. ReaderNameLabel(*): display text only, nothing happens on click
1. FocusButton(*)
   - onClick: reader gets focus, all other readers immediately lose focus
&nbsp;

1. SoloButton(*)
   - onClick: reader get solo and focus (S and F buttons on), other readers greyed out
   - A soloed reader _always_ also has focus
   - Only the soloed reader is visible in the canvas.
   - Clicking on any part of a disabled reader ends the solo. 
   - For each disabled reader, the on/off button and the solo button are still working while they are greyed out, while other sub-options under each reader are disabled.
   - During a solo, all non-soloed readers should have the visual appearance of a non-active readers
   - During a solo: if any non-soloed reader is clicked (regardless of its state), the solo should end, and the clicked reader should be enabled
&nbsp;

1. Special Keys
   - option/alt-click on any enabled reader to quickly disable all readers (see #150)

&nbsp;

_Note: (#) indicates the count of each UI element; (*) indicates one for each reader_

**Comment by dhowe** [comment]
> All the greyed-out buttons are still functionable. 

Why do you suggest this?

**Comment by cqx931** [comment]
This is my understanding of this issue: https://github.com/dhowe/ReadersJS/issues/155.
Or you are suggesting that only the on/off buttons are still working while they are actually disabled, but not other sub-options under each reader?

**Comment by dhowe** [comment]
Yes, I think the latter

**Comment by cqx931** [comment]
Please check solo buttons : 
https://github.com/dhowe/ReadersJS/pull/166

**Comment by shadoof** [comment]
closing this since we've gone live and interface is working well
