### ISSUE TITLE
FocusDisplay should 'dock' on right edge of canvas

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#167]
Seems strange that, on a wide screen, there is all the extra space between the canvas and the focus-reader display:

![image](https://user-images.githubusercontent.com/737638/27042918-02b3267a-4fcb-11e7-9d92-aac5bdd05e76.png)

**Comment by dhowe** [comment]
I think this can be closed, @cqx931 ?

**Comment by cqx931** [comment]
yes, close
