### ISSUE TITLE
FavIcon not found

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#170]
![image](https://user-images.githubusercontent.com/737638/27114917-9ceec0a8-50f9-11e7-80e6-de07ffc26621.png)

![image](https://user-images.githubusercontent.com/737638/27114941-bdbbf526-50f9-11e7-8971-39c73b48c764.png)

**Comment by cqx931** [comment]
The only clue I can find about this in ReadersWeb repo is this line:
`  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->`

Does this come from the old website? I can't remember what the favicon should look like and there is no corresponding file in the repo...

**Comment by dhowe** [comment]
why don't you create one from the current log, perhaps using only the dots:

![image](https://user-images.githubusercontent.com/737638/27130926-07fec6ae-513b-11e7-9873-9de0e0f7dd79.png)

**Comment by cqx931** [comment]
Preview images with different dot size:

![image](https://user-images.githubusercontent.com/3056154/27172323-5d86a50e-51e7-11e7-8314-b959f6ecf664.png)


![image](https://user-images.githubusercontent.com/3056154/27172302-4f6a15d2-51e7-11e7-872f-83481a252594.png)

**Comment by dhowe** [comment]
they both look good to me -- @shadoof  ?

**Comment by dhowe** [comment]
lets add the first one, before friday talk if possible @cqx931

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersWeb/pull/19
