### ISSUE TITLE
Focused reader output is invisible off bottom of page

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#178]
need to measure pixels, not number of lines

to recreate, give solo to Mesostic Jumper, and notice that the current word is often invisible off the bottom of the page (even when the window is set to maximum height):

<img width="813" alt="screen shot 2017-07-20 at 5 50 55 pm" src="https://user-images.githubusercontent.com/737638/28429253-aa7203f8-6dae-11e7-841b-a8444ca60c2d.png">

**Comment by dhowe** [comment]
I still don't see this working correctly (it is too far from the bottom in the image below): the scrolling needs to be determined by the pixel position of the lowest (newest) text, so that this is always visible, but there is not too much space beneath it:

![image](https://user-images.githubusercontent.com/737638/28486362-c9426240-6eb3-11e7-95b2-a00496be0a1d.png)

**Comment by dhowe** [comment]
also, this commit appears to have broken the line wrapping for all readers:

![spawningsimplebug](https://user-images.githubusercontent.com/737638/28630085-df290e5a-725b-11e7-8a6d-d6f5fb574f96.png)

**Comment by cqx931** [comment]
Please check the fix here: 
https://github.com/dhowe/ReadersJS/pull/183

I don't see any cut off issue though, are you referring to the horizontal cut off?
If not can you make a screen shot when you see that happening?

**Comment by dhowe** [comment]
Two separate issues -- horizontal (a regression bug) and vertical... let me verify the latter

**Comment by dhowe** [comment]
Let me clarify the vertical issue: the problem is that the most recent word is not always visible in the focused display (below the reader has just read 'And', but it is invisible off the bottom of the page).

To recreate, give solo to Mesostic, then expand the window to full height, waiting for scrolling to start, then reduce the vertical height. Notice that the most recently read word is invisible in the focus display.

![image](https://user-images.githubusercontent.com/737638/28724963-e71fc70a-7389-11e7-8f33-2290a731fa35.png)

**Comment by cqx931** [comment]
Ok, the issue is more clear to me after you latest post.
Please check the fix here: https://github.com/dhowe/ReadersJS/pull/184

**Comment by dhowe** [comment]
One of these last commits has broken the mesostic reader output (probably due to removal of &nbsp; tags). Output should look like below (with capital letters aligned, not like above):

![image](https://user-images.githubusercontent.com/737638/28749922-7493b698-74a5-11e7-8131-67707baa307b.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/185/files
