### ISSUE TITLE
add simplified chinese font to branch shanghai

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#190]
@cqx931 Sally could you checkout branch Shanghai and add an appropriate chinese font?

**Comment by cqx931** [comment]
https://github.com/dhowe/ReadersJS/pull/191
I have added one Chinese font file, but for better web performance it might be better just using the default Chinese 宋体 if they are available (SimSun for Microsoft and STSong for Mac)
http://www.kendraschaefer.com/2012/06/chinese-standard-web-fonts-the-ultimate-guide-to-css-font-family-declarations-for-web-design-in-simplified-chinese/

**Comment by shadoof** [comment]
Thanks Sally @cqx931, I've merged your pull request into my shanghai branch and the font is downloading to my computer as I write this. Thanks also for the advice above.

If I change the code to point to "image_ch.txt" (simply to make it load and display for now), do you know how to get the readers-app.js to use the STSong (mac default) font when I switch to this text using the interface, or do we have to ask Daniel?

**Comment by shadoof** [comment]
Or perhaps, for now, as a hack, @cqx931 we could just change the default for all the texts to one of the simplified chinese fonts? (I'm trying to figure out how to do this, but am not yet sure how.)

**Comment by cqx931** [comment]
For the canvas, only this line need to be changed to the Chinese font. 
https://github.com/dhowe/ReadersJS/blob/master/src/multi-page.js#L7

What's your plan for the rest of the page?

**Comment by shadoof** [comment]
Thanks @cqx931 Sally, I will have a go and sort out page display. I know the trigrams need to be loaded but I have, I think, a hack for that also.

I have to go out with the poets here now, but hope to find some time to work on this later.

NB: I'm keeping all this on the shanghai branch, in case this isn't obvious.

**Comment by shadoof** [comment]
@cqx931 Latest commit on shanghai branch will to (broken) display of characters for 'The Image'. My question is: what is the times17.js file with font metrics doing (normally)? Is it applied to the Baskerville?? So I ignore it?

**Comment by dhowe** [comment]
dont need any font-metrics in the current version

**Comment by shadoof** [comment]
closing this to open with other shanghai issues
