### ISSUE TITLE
shanghai branch: "no trigrams" error for Chinese image text

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#192]
* try to find a quick fix for this so that the MarkovJumper will at least read through the Chinese text like a simple reader, then ...

... John will generate data allowing this reader to act, eventually, as a 'Markov Jumper' (may leap ahead in the text to where other NL collocations - existing in the text itself - occur)

**Comment by dhowe** [comment]
maybe just disable that reader until you have the data?

**Comment by shadoof** [comment]
closing this, since the only current 'shanghai' reader is not using bigrams, but has been kitted out with some Very Basic (internal-to-the-text) bigrams (thanks to nltk ...)
