### ISSUE TITLE
Best place and practice for writing up notes to be shared for this repo?

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#194]
I need to write some notes on the Chinese readers since, if we are to be serious about them, we'll have to do some more research and work. Hoping Sally will be up for helping with this.

**Comment by dhowe** [comment]
how about a Chinese.md in the top-level directory?

**Comment by shadoof** [comment]
Fine by me. Would you prefer this, as opposed to using the Github Wiki tab?

**Comment by dhowe** [comment]
Actually, yes, I prefer your suggestion... as it keeps the directories for code only
Perhaps we can also move the ReadingLA_ELOPorto2017.md file to the wiki as well, if its still needed?

**Comment by shadoof** [comment]
OK, I'll move the ReadingLA_ELOPorto material and also get on with a Chinese readers page.
