### ISSUE TITLE
Need 'loading' animation (page load is very slow the first time)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#20]
Note: should also try to load trigram resources async (@dhowe)

**Comment by cqx931** [comment]
Loading animation added. Please check: https://github.com/dhowe/ReadersJS/pull/22

**Comment by dhowe** [comment]
this doesn't really do what we need -- check it on the live site: http://thereadersproject.org/live/
during the long wait time (make sure to clear your browser cache), the page is blank white

**Comment by cqx931** [comment]
I see... let me check again.

**Comment by cqx931** [comment]
Could you try this? https://github.com/dhowe/ReadersJS/pull/23

**Comment by dhowe** [comment]
Desired Behavior:
------------------------
- loading animation starts as quickly as possible (ideally immediately) and continues until necessary files for the first text ONLY are loaded
- then the app starts
- if the users switches to another text before the data for that text has loaded, then they get the loading animation again, but they should only need to wait for the data for that one text
- then the new text start

So in rare cases of quick text-switching, the user could see a max of 3 separate loading animations

**Comment by cqx931** [comment]
Please check the loading animation according to the above requirement:
https://github.com/dhowe/ReadersJS/pull/29

1. I added the other two trigram script dynamically for now. It was easier for me to control the time sequence in in this way. But maybe you can also check whether it works with "async" or "defer" attribute.

2.I was able to get the animation working, but there is one thing remaining.
I didn't get to call textChanged in finishLoading(). [Please see here](https://github.com/cqx931/ReadersJS/blob/master/index.html#L76)

textChanged is currently inside createInterface() and I am not sure what is the best way to change the code if I want to call it outside the scope.

**Comment by dhowe** [comment]
> textChanged is currently inside createInterface() and I am not sure what is the best way to change the code if I want to call it outside the scope.

simply move it into multi-page.js

**Comment by dhowe** [comment]
Still seeing very slow load times (over 10 seconds) before first text starts.
Please verify:

1) loading animation starts immediately
2) loading animation ends after js and first trigram files are loaded
3) 2nd and 3rd trigram files after loaded AFTER the page is running
4) should be possibly to go the 'the image' BEFORE its trigrams are loaded (2nd loading animation)

**Comment by cqx931** [comment]
done
