### ISSUE TITLE
Add temporary "In progress" text/icon at top of index.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#21]
as we have already submitted the live url (http://thereadersproject.org/live/) to a festival

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/22

**Comment by shadoof** [comment]
I think that "Under Construction" might be better than "In Progress" (less ambiguous)

**Comment by dhowe** [comment]
agreed... 
maybe we should have one of those construction worker gifs like in the 90s :)
