### ISSUE TITLE
Errors on Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#24]
Note that we need to test this interface in all popular browser, including firefox and opera.
Some things already seem not to work in FF, and there are errors in the console (line 91 of index.html):

<img width="451" alt="screen shot 2017-03-14 at 4 42 19 pm" src="https://cloud.githubusercontent.com/assets/737638/23892389/529c0338-08d5-11e7-9e31-6fc2afd85fc9.png">

**Comment by cqx931** [comment]
Does it work at least in Chrome now?

**Comment by dhowe** [comment]
i wasn't able to test before, but yes looks good... the problem now is that it takes FOREVER to load

**Comment by cqx931** [comment]
10MB is a huge file to load...Anyway, I will first check it with other browsers.

**Comment by cqx931** [comment]
Strange, the page works well for me on firefox.

**Comment by dhowe** [comment]
FYI, the error above doesn't have to do with loading, but with the interface itself...

**Comment by cqx931** [comment]
Fixed, tested in firefox, opera, chromium and safari.
https://github.com/dhowe/ReadersJS/pull/29
