### ISSUE TITLE
Need to define appropriate speeds for Readers

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#27]
in multi-page-ui.js
![image](https://cloud.githubusercontent.com/assets/737638/23898586/6b9fd096-08ec-11e7-8f1f-03e9148c795a.png)

**Comment by shadoof** [comment]
Based on the recent Java implementation, I say:

Speed | Secs
-|-
Fluent | 0.4
Steady | 0.8
Slow | 1.2
Slower | 1.6
Slowest | 2.0
Fast | 0.2

**But Note**: to make the reading *much* more organic seeming, the Java implements a speed variation based on the number of syllables of the word-being-read. The code for this is:

```
adjustSpeed(1 + (countSyllables(RiTa.getSyllables(wordString)) - 1) * .3f);
```
where `adjustSpeed()` passes a factor applied to the Reader's current speed such that a single syllable word is read at the base speed (factor = 1) and a two-syllable word would be read at a factor of 1.3 and a three-syllable at 1.6 etc. 

Suggested initial starting speeds for Readers:

Reader | Initial speed
-|-
PERIGRAM READER | Fluent
LESS DIRECTED PERIGRAM READER | Steady
SIMPLE SPAWNING READER | Slow
PERIGRAM SPAWNING READER | Slow
LESS DIRECTED PERIGRAM SPAWNING READER | Slow
MESOSTIC READER | Steady

**Comment by dhowe** [comment]
Sounds good -- please add to the code...
