### ISSUE TITLE
Handle paragraphs without indents

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#34]
![screen shot 2017-03-14 at 2 28 02 pm](https://cloud.githubusercontent.com/assets/1051808/23916420/85d6bde6-08c2-11e7-886b-c9d4ed92dcf1.jpg)

**Comment by dhowe** [comment]
Controlled by default options at top of multi-page.js:

```
  RiText.defaults.paragraphLeading = 10;
  RiText.defaults.paragraphIndent = 0;
```

![image](https://cloud.githubusercontent.com/assets/737638/25049062/6800ae76-2172-11e7-8c6e-b683a7bbb931.png)

**Comment by dhowe** [comment]
@shadoof please verify and close...

**Comment by shadoof** [comment]
Looks good to me.
