### ISSUE TITLE
issues with fading

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#36]
@dhowe I've done the perigram reader visual behavior as it was before, but: when a perigram reader back-tracks enough to encounter fades that are still in progress (usually they are fading back to the default grid fill color) then undesirable artifacts arise:
* unwanted behavior: I believe that a new(er) fade (ColorTo()) rightly 'cancels' an ongoing fade, but to do so first sets the affected word (the ritext) back to the grid default fill color quickly (instantly?) and then starts the new fade
* desired behavior: the older ongoing fade is stopped where it is and the newer fade takes over from that color point, fading in to its new ColorTo() destination.

**Comment by dhowe** [comment]
and this works correctly in java version?

**Comment by shadoof** [comment]
@dhowe Answer is no. But in the Java version, somehow, the issue is generally less intrusive, visually. I'm sure this is a tough one to solve conclusively but it would be worth it: the thing is to realize the following pseudo code:
```
initiate fade on ritext a;
if (another fade is already running on ritext a)
  stop this previously requested fade in its tracks;
  effect the newly requested fade as a ColorTo() from ritext a's interrupted state;
else
  do the requested fade;
endif
```

**Comment by dhowe** [comment]
go it... i'll take a look

**Comment by shadoof** [comment]
something that just occurred to me to mention @dhowe in case it's relevant and overlooked. if a running fade that needs to be interrupted is in a 'delay' state (delay-waiting before fading), are these detected? If not, then they should be: they should also be cancelled and the new fade should be imposed.

**Comment by dhowe** [comment]
on my schedule for sunday

**Comment by dhowe** [comment]
I've made a fix, but I need some kind of test case to verify

**Comment by shadoof** [comment]
setting up a test rig would, I think, be pretty difficult. I could probably tell if it's working since I've spent so much time watching the VB's.

If we temporarily nobbled a perigram reader such that it only went east, this would guarantee quick confirmation of any artifacts since fades would definitely interrupt early fades as soon as the reader got to the end of a line ...

**Comment by dhowe** [comment]
I'm closing this, however I am not sure that all cases of delayed fades are fully covered (but if we find a problem, we'll re-open with a test case)
