### ISSUE TITLE
Change colors, fonts, sizes, etc to match Java app

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#4]
First see #1, then check out the apps here:

http://thereadersproject.org/elc3.html#ELC3

**Comment by cqx931** [comment]
The Java app have five colors to choose and it doesn't match with a specific reader.
Shall I choose two colors from the color palette or what is your plan?

By sizes, do you mean both font-sizes and canvas sizes?

**Comment by dhowe** [comment]
Yes, the goal is to have the two apps be as similar as possible. Though feel free to suggest other design decisions (e.g., for the buttons)...

**Comment by cqx931** [comment]
I see... Then I will also change the opacity of the main text...
What buttons do you mean? The user interface? Does the JS version also supposed to support changing readers, text and colors?

**Comment by dhowe** [comment]
The goal is to replace the Java version completely...

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/5 
I have implemented the font, sizes and picked two colors for the readers.
Let's discuss later about this.

**Comment by shadoof** [comment]
@dhowe - can we be sure to get/allow non-indented paragraphs and paragraphs with blank lines in between? (I'm thinking of 'The Image' here.)

**Comment by dhowe** [comment]
can you provide  a screenshot of what it should look like ?

**Comment by shadoof** [comment]
@dhowe 
![screen shot 2017-03-14 at 2 28 02 pm](https://cloud.githubusercontent.com/assets/1051808/23916420/85d6bde6-08c2-11e7-886b-c9d4ed92dcf1.jpg)

**Comment by dhowe** [comment]
can this be closed?

**Comment by shadoof** [comment]
Remaining differences @dhowe (none of these are crucial, although I think all these changes would be good):
* the Java app opens with Poetic Caption as the initial text
* in the Java app, Misspelt Landings is set in GillSansMT-24

The Image is now set as desired, so if you or Sally don't want to do either of the above, this could be closed.

**Comment by dhowe** [comment]
closing for now, if you want either of the two items above, just create another ticket (@shadoof)
