### ISSUE TITLE
Visual effects are frozen (fades suspended) if they are not visible

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#47]
I think this also applies to readers which are occluded by the interface panel, but the chief unwanted symptom is manifested (most clearly) by doing the following:
1. turn off all but one reader
2. hit a right or left arrow key until this reader is not visible
3. wait for a little while to allow for the reader to change its position by a couple of lines
4. use arrow keys to make the page with the reader visible again.

You will see the frozen fade-traces of the reader before step 2.

**Comment by dhowe** [comment]
this is strange -- any hypothesis?

**Comment by dhowe** [comment]
@shadoof please confirm fix

**Comment by shadoof** [comment]
@dhowe seems to me to be fixed!
