### ISSUE TITLE
Move focused-reader to top of verso if invisible after page-flip

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#52]
Keeps the focused reader always on verso or recto, which might also solve #35 in that it would allow an expert user to put that reader on any page...

@shadoof ?

**Comment by shadoof** [comment]
thought about this for a while and decided: yes, is a good idea I think

**Comment by dhowe** [comment]
@shadoof please verify (and close if ok) in a5f117a1c

**Comment by shadoof** [comment]
Basic functionality is in place and works. Two issues:
* When a non-focused reader that is currently invisible (it's on a non-visible grid) is double-clicked, it does not yet jump to the visible verso ... and it should. (No page change is needed.)
* We do seem to have a new-js-implementation version of the problem that we encountered with the Java applications, viz: visual behaviors are not run (human-visibly) on the first word of a grid when a reader is moved to the top of the grid. (ie: the focused reader does jump to the top of a new verso but we only see the 2nd word faded-in to the reader color)

**Comment by dhowe** [comment]
Splitting into two new tickets
