### ISSUE TITLE
Reader-display overlaps main display on narrow screen

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#54]
![image](https://cloud.githubusercontent.com/assets/737638/24329993/b75d8668-1247-11e7-96b2-65b8e85ccf0a.png)

see also #50

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/60/commits/52518af20c84389539a01cfb06c0aca17d22dfcb

I added two features trying to solve this:
1.The Reader Display got different styles for screen width > 1500px and screen width < 1500px
2.The display is now collapsable
