### ISSUE TITLE
Empty focused log for Perigram Readers

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersJS#59]
In https://github.com/dhowe/ReadersJS/pull/57, this line of code has been commented out from perigram-reader, also from spawning simple reader and other kinds of perigram reader (spawning and oneway).  
 ` this.consoleString = (neighbors[this.wayToGo].text() + " (" + Grid.direction(this.wayToGo) + ") ");` 

Is there any particular reason for this?
Now if the readers above get focused, the loggging on the right hand side will be empty because consoleString is always an empty string.
Or are the logs from new readers waiting to be adjusted to different formats? @shadoof

**Comment by dhowe** [comment]
Yes, we need to attend to the output for many of the readers, to make sure they are formatted correctly, etc. I've looked at Mesostic, but not the others. Spawned readers (like the oneway) should not have output, as they cannot get focus.

**Comment by shadoof** [comment]
closing this – no longer 'empty'. I'll be working on the output for the Perigram and related readers. New issues as they arise.
