### ISSUE TITLE
Better sequence for Mesostic

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#64]
any thoughts @shadoof -- currently it is 'Its Over Its Done'

**Comment by shadoof** [comment]
in the Java application, I implemented per-text sequences for the Mesostic readers:
* misspelt -> "reaching out falling through circling over landing on turning within spelling as"
* poetic -> "reading as writing through"
* image -> "comes in is over goes out is done lolls in stays there is had no more"
