### ISSUE TITLE
Add hide option for focus-display 

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#69]
maybe just an X next to the title?
also perhaps a hide/show toggle in the main interface so that it can be brought back?

**Comment by cqx931** [comment]
It can now already be hidden (slideToggle) by clicking the focus-display title.
If that is not obvious I can show the display with a slideToggle so to give a hint?

**Comment by dhowe** [comment]
I thought that might be the case, however nothing happens for me when I click it
Also, while you are there, please clear that display whenever onTextChange() is called

**Comment by cqx931** [comment]
This is strange... it works well for two screen width case, with latest commit, both in chrome and chromium.
