### ISSUE TITLE
focusDisplayTag should be the color of the currently focused reader?

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#70]
![image](https://cloud.githubusercontent.com/assets/737638/24395148/3e4753b8-13d1-11e7-995a-5c377bcd2155.png)

**Comment by dhowe** [comment]
perhaps the text as well, though that may be too much (@shadoof are you working on output for the other readers?)

**Comment by dhowe** [comment]
perhaps we should also strip punctuation from the ends of Mesostic outputs (2 cases in image above)?

**Comment by shadoof** [comment]
I'd say: yes. This punctuation is not relevant when reading the output.

**Comment by shadoof** [comment]
> perhaps the text as well, though that may be too much (@shadoof are you working on output for the other readers?)
@dhowe have prepared ground for output from the Perigram Reader and descendent and I wrote the simplest of textForServer() functions for the actual Perigram Reader but ... nothing appears in the sidebar and I don't know how to make this happen.

**Comment by shadoof** [comment]
and I can no longer get this window to close

**Comment by cqx931** [comment]
Color has been added to focusDisplayTag
