### ISSUE TITLE
Use 'Light-on-dark' and 'Dark-on-light' for Theme names

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#77]
... to avoid ambiguity of 'Dark' for Style and, I'd suggest:
* for Style use 'Not visible' or 'Invisible' instead of 'Dark' (because this will work for the 'Dark-on-light' Theme

**Comment by dhowe** [comment]
I prefer 'Invisible'...

**Comment by dhowe** [comment]
![image](https://cloud.githubusercontent.com/assets/737638/24417921/dd84a6ce-141c-11e7-82fd-026a26078302.png)

![image](https://cloud.githubusercontent.com/assets/737638/24417933/ebc989c0-141c-11e7-84bd-94d64c3d629e.png)

**Comment by cqx931** [comment]
Currently we have the following percentage for opacity for the three style:
```
Faint: 40,
Grey: 70,
Invisible: 0
```

>  I would argue for a brighter default set (maybe not quite as bright as below), then give the user two other options, one dimmer, like the first image, one brighter still...

For what you suggested above, I think we need to remove the invisible style and the settings would be:

```
Default: 50,
Grey: 70,
Faint: 30
```

**Comment by shadoof** [comment]
I'm closing this. @dhowe @cqx931 - I strongly feel that we stick with what we have now:
* for Style:
```
Faint: 40 [opening default]
Grey: 70
Invisible: 0
```
where these are all alphas. Stick with this code-internally. *For the UI only*, possibly, it might better to have 'Title' for current 'Text' and 'Text' for current 'Style' since this might make more sense to human readers.
* for Theme: stick with 'Dark' or 'Light' and code internally use the global bgColor variable to work out which theme we are in. Dark theme works and I'm pretty sure I can make the VB's for the Light theme work easily now we have Color objects.
