### ISSUE TITLE
the default Style is - correctly - 'Faint' but onload the actual style is 'Gray' ...

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#79]
... and implement US spelling for 'gray' throughout? ;)

**Comment by dhowe** [comment]
we were trying to help you convince people you are really british...

**Comment by dhowe** [comment]
but either is fine, we just need to be consistent throughout 

the texts/bigrams/trigrams use 'grey' only

**Comment by shadoof** [comment]
Given the spelling in the texts, let's use 'grey' throughout.

**Comment by shadoof** [comment]
closing this. make separate new issues for anything related
