### ISSUE TITLE
Design Mockups

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersJS#8]
One important question is, now that we have multiple readers, whether we need to let the user assign colors and behaviors to each, or if instead we pick the best color and behavior for each, which would greatly simply the interface. The designs below assume the more complex users-choice interface:

<br>

Step 0
![image](https://cloud.githubusercontent.com/assets/3056154/23064102/10a5391c-f549-11e6-8821-91a7cdc45b4b.png) 

Step 1: Click to see menu
![image](https://cloud.githubusercontent.com/assets/3056154/23064107/157d1b44-f549-11e6-9353-8e7121c8091e.png)

Step 2: Hover to see "Options" button
![image](https://cloud.githubusercontent.com/assets/3056154/23064112/19796e82-f549-11e6-88ed-8e237e066cac.png)

Step 3 : Click "Options" to see sub menu
![image](https://cloud.githubusercontent.com/assets/3056154/23064119/1df4cbc8-f549-11e6-84e0-1b431ecaa75d.png)

Step 4: Click item to change
![image](https://cloud.githubusercontent.com/assets/3056154/23064124/23af9476-f549-11e6-9771-6505ff720fa2.png)

**Comment by cqx931** [comment]
Relative size to the whole page:
![image](https://cloud.githubusercontent.com/assets/3056154/23064135/3278f290-f549-11e6-95d0-5abebd6c57ea.png)

**Comment by dhowe** [comment]
when is the larger 'readers options' button visible?
and what happens if you click one of the Reader names (e.g., Mesostic Reader)?

**Comment by cqx931** [comment]
- The larger 'readers options' was designed to be always visible.
- Click on the Reader should do nothing; Clicking the circle before to enable/disable
- So the text/article changing function only works for all the readers instead of for each reader right?
- Do we still want to show the current word for each reader if we are showing them simultaneously? It doesn't make sense to put it in the options menu, but I also think there will be too much information if we them altogether.

![image](https://cloud.githubusercontent.com/assets/3056154/23065344/0e26c578-f550-11e6-891d-4006b1dd9f54.png)

**Comment by dhowe** [comment]
`So the text/article changing function only works for all the readers instead of for each reader right?`
Correct.

@shadoof do you want to chime in here?

**Comment by shadoof** [comment]
This is all very much on the way to looking good. My principles:
- maintain option for a clean, full-screen, 'chrome'-less display.
- allow the reader-configuration of all the readers (why not? readers need to be able to learn how the readers reader and being able to configure them - slow them down, make them more visible, etc. - helps with this)
- distinguish clearly between menu or option items which are active/selectable and those that are giving information (e.g. in the immediately above 'PAGE' should also be operative and allow the pages (=opening/spread) to be configurable. I think the idea of giving info on which pages are displayed is good.
  Specifics:
- There should be top-level operative menu options for 'TEXT', 'READERS', and 'OPENING' (to replace 'PAGE')
- 'TEXT' allows the text to be changed for *all* readers: yes.
- the 'TEXT' menu also allows users to configure the colour/shade of the text being read: 'Faint', 'Dark', 'Gray', as well as selecting from the existing text options.
- the 'READERS' menu shows all the possible readers and also allows for setting one reader as the focused or page-turning reader.
- having filled-in bullets for those readers that are active is an excellent and intuitive idea for me.
- having 'options' buttons appear for any active readers (and not for the others) is also good.
- although it would also be perfectly possible to have background highlighting for the 'focused'/'page-turning' reader and then to allow a single reader-option or cascading menu item for all the other possible reader configuration parameters.
- if we maintained the active menu item, plus (distinguishable) information display, then I think it would be good to have a corresponding 'READERS' info display item that showed: the name of the focused reader and all its other configurable options (those that are not obvious - no need to show color because readers see this) such as what word it is reading and - *new* - its coordinate position on the grid.

**Comment by dhowe** [comment]
I'm starting to think that before we build in every possible option, we may want to consider what we want the user to focus on, and try to minimize extraneous options beyond that. I worry that so much 'choice' will detract from the close reading of a) reader strategies, b) the text itself, and c) reader output, which are, at least for me, most important...

**Comment by cqx931** [comment]
Oh, I misunderstood the page turner as something to set the current page.
I prefer the word "focus" for the focused reader/ page turner. For me, "page turner" is a bit too long for layout and less straight forward than "focus".
There is already a page number showing on the bottom of each page, so I think there is no need to add any more hint.

![image](https://cloud.githubusercontent.com/assets/3056154/23099419/337b61ba-f6a1-11e6-9205-bbb8749a752c.png)

I also agree to show minimum information when the user first sees the menu. More information could show up when the user needs them (triggered by interaction).

**Comment by shadoof** [comment]
Interface is looking steadily more readable. Great stuff.
This is to respond, chiefly, to Daniel's suggestion that we strategically limit configurable options. I am tending to agree but there are certain options that I believe need to be maintained. Here, I attempt to set out what I'd like to see in there. Please read, below, indenting as correlating with the menu hierarchy:
TEXT <text_name>
     <selectable_text_name>
     <selectable_options_for_the_text's_colour: 'Faint' | 'Invisible' | 'Cray'>
     <selectable_toggle: 'Invert' (which toggles back and forth from w-on-b to b-on-w, also handling
        any necessary changes in Reader color)>
READERS <currently_focused_reader_name>
     <activate readers by click the bullet(s) beside its name>
     <select and highlight a 'focused' reader that also turns pages and supplies any widgets that
       monitor what it is reading>
     <select=set_speed_of_focused_reader: speeds as they are for the java sketch>
     PERIGRAM READER
     LESS DIRECTED PERIGRAM READER
     SIMPLE SPAWNING READER
          NE & SE
          South-East
          North-East
     PERIGRAM SPAWNING READER
          NE & SE
          South-East
          North-East
     LESS DIRECTED PERIGRAM SPAWNING READER
          NE & SE
          South-East
          North-East
     MESOSTIC READER
GO <see below>

Thus the spawning directions for spawning readers are still user-configurable, but the color and 'visuals' (traces or haloes) of these readers are hard-coded, as follows:
     PERIGRAM READER - traces
     LESS DIRECTED PERIGRAM READER - haloes
     SIMPLE SPAWNING READER - neither traces nor haloes (just spawning-traces)
     PERIGRAM SPAWNING READER - traces
     LESS DIRECTED PERIGRAM SPAWNING READER - traces
     MESOSTIC READER - <Daniel's call: traces not relevant; haloes possible>

This is not meant to suggest design or precise mechanics for the menu system, only to indicate what parameters I think should still be user-configurable.

As you see, I do think that there could be a top-level "GO" menu that displayed opening and page and grid-coordinate information for the focused reader and allowed a user to move the focused reader (perhaps also relative-shifting all the others) flexibly.

**Comment by dhowe** [comment]
This make sense to me. So we have as the most basic options:

- Text Config (text, color)
- Reader Config (on/off for each, speed for each, one gets focus)
- Go (starts focused-reader at start of text)

Each reader then gets a hard-coded single behavior, and, potentially, a different color for each of the text color options. I would argue for picking the most interesting (spawning) direction for each and hard-coding it for now.

Notes/Questions:
- Not sure that we need an invert button, but if so, it should just switch between existing color options
- Not clear how non-focused readers are distributed on pages when 'Go' is pressed (maybe just random across other pages?)

@cayley if this makes sense to you, we can do a quick mockup

**Comment by shadoof** [comment]
Yes, makes sense to me. Go ahead with a quick mockup, I'd say.
* Invert is desirable due to differing possible display conditions. Not sure what you mean about making this a part of switching between colour option. Background colour (really shading) of the supply texts (Faint, Gray, Dark) would have inverted corresponding values. The (fixed) colors of the readers should also have inverted corresponding values (so that the corresponding inverted colors also look against a white 'paper' background and in relation to the different inverted shadings of the supply text color.
* Non-focused reader positions. Ideally, within reason, these should be configurable at least to (suggestions): top of an arbitrary page, middle of an arbitrary page, ahead of the focused reader, behind the focused reader (so that human readers can see the effects of reader interactions).

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23536980/d3acf55c-0003-11e7-94df-e3a2972b41b5.png)

For now the interface only has 3 interactive elements:
1. The circle to switch on/off the reader
2. Clickable gray box for settings
3. Button (Gray border without fill)

For the invert toggle I have used the expression "Dark theme/Light theme", which I think is more easier to understand. This is just a suggestion, if you have other opinions, I can change it to something else.

For all the gray boxes, if the user clicks it, a dropdown shows up like below:
![image](https://cloud.githubusercontent.com/assets/3056154/23536839/c1c33e2e-0002-11e7-8b60-15a4e8eda898.png)

**Comment by dhowe** [comment]
Works for me. Where does one see the focused readers output?

**Comment by cqx931** [comment]
I'm not sure what you mean exactly by "focused readers output", isn't this just an interface and the output is going to be on the main canvas?

**Comment by dhowe** [comment]
On the main canvas, we have the readers moving through the text, one of which is focused, which means that a) it controls page-turns, and b) we can see the words/phrases it select separately. Something like:

![image](https://cloud.githubusercontent.com/assets/737638/23538546/f8d6eb20-000e-11e7-8825-29ff19384469.png)

**Comment by cqx931** [comment]
So you mean how can the user know which among the several readers is the focused one?

**Comment by cqx931** [comment]
I have implemented the interface according to the mockup.
Please check https://github.com/dhowe/ReadersJS/pull/9
The right hand side is a first-try of the word-by-word output of the current reader.
We can discuss about it more in details.
As we are having a "GO" button,  is it true that changes will only be made if the user clicks the button? Will there be any immediate feedback or preview?

![image](https://cloud.githubusercontent.com/assets/3056154/23789089/561d5e7c-05b4-11e7-8165-3cd64059934e.png)

**Comment by dhowe** [comment]
This is a good start. A few things:

- We need the colors of the buttons in the interface to map to the actual reader colors
- Clicking off the menu should close it
- "TITLE" should be "TEXT"
- I wonder if we need the 'GO' button -- why not try with all changes happening in real-time?

@cayley?

**Comment by cqx931** [comment]
Here is a proposed color scheme based on the main reader color scheme as well as the color scheme used in ELC3. 
![image](https://cloud.githubusercontent.com/assets/3056154/23819858/87b3e9e0-0647-11e7-9299-bb6afe11ab7d.png)

**Comment by dhowe** [comment]
Sorry, which are the proposed colors? We have 6 readers, so need 6 colors for each style/theme...

**Comment by cqx931** [comment]
the color in the dots are the proposed colors.
Colors on the right hand side was the color scheme used before.

**Comment by cqx931** [comment]
Please check some new update: https://github.com/dhowe/ReadersJS/pull/10
I'm not sure where is the best place to change the fill() for the whole page, is there any hint? @dhowe

**Comment by shadoof** [comment]
Looking better and better.
* dhowe's question: Yes we should have distinct colors for each of the readers that change per-reader when the theme changes.
* when the filled dot-color of an active reader is clicked, I think that the color should immediately fade to black despite the mouse (immediately after the click) still being hovered over the dot. Once the cursor leaves the inactive dot, it obviously stays black and only when the cursor *returns* to hover over an inactive dot should it fill (offering its active color)
* I agree that we should not need the 'Go' button and that changes should be live, but ...
* there are no reader-navigation or reader-placement menu items yet, are there? I think we need some of this, down the line
* I think 'Spawner' is awkward especially 'Spawner Reader'. I think we should use 'Spawning Reader' in all cases.

**Comment by dhowe** [comment]
> * when the filled dot-color of an active reader is clicked, I think that the color should immediately fade to black despite the mouse (immediately after the click) still being hovered over the dot. Once the cursor leaves the inactive dot, it obviously stays black and only when the cursor *returns* to hover over an inactive dot should it fill (offering its active color)

see #15

> * there are no reader-navigation or reader-placement menu items yet, are there? I think we need some of this, down the line

I don't see the utility of this -- can you describe the use-case you imagine?

> * I think 'Spawner' is awkward especially 'Spawner Reader'. I think we should use 'Spawning Reader' in all cases.

Agreed

**Comment by shadoof** [comment]
>> * there are no reader-navigation or reader-placement menu items yet, are there? I think we need some of this, down the line

> I don't see the utility of this -- can you describe the use-case you imagine?

I think there will definitely be times when human readers will want to move the readers around (start again; re-examine interactions; check that the paths through the texts are or are not determinative). The 'Go' item could, instead be a 'Move focused reader to ...' item, that dropped do to:
* beginning of current text
* beginning of current page
* * beginning of page ...
