### ISSUE TITLE
Switching to new text should auto-close menu ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#80]

**Comment by shadoof** [comment]
I'd say: yes.

**Comment by cqx931** [comment]
Why auto-close menu only for switching to new text?

**Comment by dhowe** [comment]
Its like restarting everything. I notice in my use that I expect it to close after changing texts (otherwise, for one, I can't see that the text has changed).

**Comment by cqx931** [comment]
I don't really expect it to close here but I'm also not against it.
So here is the fix: https://github.com/dhowe/ReadersJS/pull/85/commits/f291bdd9b1ae1b5a32abe29ac3f3b4deae249de9
