### ISSUE TITLE
double-clicking a Reader button highlights the first word of its name

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersJS#82]
Shouldn't really do this. Shouldn't be possible to highlight/select the text of the interface.

**Comment by dhowe** [comment]
Same for the Focused Reader display title..

**Comment by cqx931** [comment]
Thanks for pointing this out! Here is the fix: https://github.com/dhowe/ReadersJS/pull/85/commits/af5086b71bb11b6ba4d38cb1d55fe7bfba7f5fc7
