### ISSUE TITLE
Finalize Color Scheme

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersJS#87]
![image](https://cloud.githubusercontent.com/assets/3056154/23819858/87b3e9e0-0647-11e7-9299-bb6afe11ab7d.png)

![image](https://cloud.githubusercontent.com/assets/3056154/24450105/2a4fc148-14ac-11e7-92a0-3dcfcfa084ce.png)

The first image is my original color scheme while the second is the Reader.COLORS variable in `readers-app.js`

Have we changed "Less Directed Spawner" in java to "One Way Perigram Reader"? If yes, I need to modify the color scheme accordingly.

My idea behind the color scheme is to group the readers with colors.
The basic idea behind is:
Perigram - Red
Mesostic - Blue
Spawning - Yellow

So for "Spawning Perigram Reader" it is a mixture of red and yellow -> orange.

Currently I found that the difference among different shades of red / yellow is hard to recognize. If you all agree, I can try a color scheme that is more obvious to recognize different readers. (Ex: Pinkish red...)

**Comment by dhowe** [comment]
For me, it is more important that the colors are clearly different, rather than that certain types of readers are similarly colored... So yes, I think try a new scheme focusing on a) clear differentiation and b)  an aesthetically pleasing palette

**Comment by shadoof** [comment]
@cqx931 agreeing with Daniel above and, to answer question, in this implementation there is no 'Less Directed Spawner" (the only spawning readers are Simple and Perigram)

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/24489775/e6f0ad08-1551-11e7-95e2-097415ecd55b.png)

**Comment by shadoof** [comment]
still needs some work I think - not convinced pink for the Oblique reader

**Comment by dhowe** [comment]
that was the one question mark for me, though it is nicely distinct

**Comment by cqx931** [comment]
Update the new yellow and orange color, please also take a look at this new pink:
![artboard 2](https://cloud.githubusercontent.com/assets/3056154/24589019/f1c1a28a-1805-11e7-9263-c1aa5849a8c6.png)

**Comment by dhowe** [comment]
@shadoof can this be closed?

**Comment by shadoof** [comment]
@cqx931 To my eye the yellow of the Spawning Simple Reader needs to be a little darker (tinged with something) under the Dark theme; and under the Light theme it needs to be quite a bit darker and more distinct (more contrast with the white background). Then, yes, this could be closed.

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/25064036/a7ca4a5a-2224-11e7-968d-2caaaa8186c9.png)

**Comment by shadoof** [comment]
@cqx931 These colors (that look good and like they'd be better) have not yet been implemented and merged into the master branch, right? Looking forward to them. (But we will not use those pink tones for One Way Perigram Readers: we will stick with the current grey's for spawned readers of this type.)

**Comment by cqx931** [comment]
yes, they have not yet been implemented. I will update the colors accordingly.

**Comment by cqx931** [comment]
https://github.com/dhowe/ReadersJS/pull/131/commits/ebda1bd1b91552e2b52ce94b3873c466d0f2a235 Please check
