### ISSUE TITLE
Yellow and Orange reader colors are too close

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#95]
Appears on start, as if there are two SimpleSpawners (one on each page):

![image](https://cloud.githubusercontent.com/assets/737638/24586612/b5e2a832-17d7-11e7-85a0-e60f3663c29c.png)

**Comment by cqx931** [comment]
Is this obvious enough?
![image](https://cloud.githubusercontent.com/assets/3056154/24587485/3e103e74-17ea-11e7-8834-7b75aceacba6.png)

**Comment by dhowe** [comment]
much better, @shadoof ?

**Comment by shadoof** [comment]
@dhowe agreed
