### ISSUE TITLE
Focus-Display margin breaks mesostic output

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#98]
its important the widest mesostic selection doesn't break into two lines (as below) -- perhaps just reduce the margin a bit and add a few more pixels width to the column ?

![image](https://cloud.githubusercontent.com/assets/737638/24588691/fa5cc006-17ff-11e7-8284-742b7be8edf8.png)

![image](https://cloud.githubusercontent.com/assets/737638/24588708/60e6d816-1800-11e7-80c6-97425b582c54.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ReadersJS/pull/99
